name: Download and Upload Artifact

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  
jobs:
  download:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    strategy:
      matrix:
        architecture: [x86-64, aarch64]
        os: [unknown-linux-gnu, apple-darwin]

    steps:
      - name: create directory
        run: mkdir -p artifact
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: $godata_server-${{ matrix.architecture }}-${{ matrix.os }}
          path: artifact
      - name: create single archive
        run: zip -r -j godata_server.zip artifact/*
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: './godata_server.zip'
      
      